"use client";

import Link from "@/components/localized-link";
import { ArrowRight, Facebook, Instagram, Linkedin } from "lucide-react";
import { useLanguage } from "@/components/language-provider";
import { marketingCopy, marketingServices } from "@/lib/marketing-content";

export function MarketingHome({ onOpenModal }: { onOpenModal: (service?: string) => void }) {
  const { locale } = useLanguage();
  const c = marketingCopy[locale];
  const direction = locale === "ar" ? "rotate-180" : "";
  return <main id="main-content" className="refresh-home">
    <section className="refresh-hero section-wrap">
      <div><p className="refresh-label">{c.eyebrow}</p><h1 className="display refresh-hero-title">{c.title}<br /><span>{c.accent}</span></h1><p className="refresh-intro">{c.description}</p><div className="mt-8 flex flex-wrap items-center gap-x-7 gap-y-4"><button onClick={() => onOpenModal()} className="focus-ring refresh-primary">{c.primary}<ArrowRight size={17} className={direction} /></button><a href="#build" className="focus-ring refresh-link">{c.secondary}</a></div><p className="refresh-location">{c.location}</p></div>
      <aside className="refresh-directory" aria-label={c.index}><p className="refresh-label">{c.index}</p><div className="mt-5">{marketingServices.map((s, i) => <Link key={s.slug} href={`/services/${s.slug}`} className="focus-ring refresh-directory-link"><span className="refresh-number">0{i + 1}</span><span>{s[locale].title}</span><ArrowRight size={16} className={direction} /></Link>)}</div><p className="mt-6 text-sm leading-relaxed text-muted">{c.indexNote}</p></aside>
    </section>
    <section id="build" className="section-wrap refresh-section"><div className="refresh-section-heading"><div><p className="refresh-label">{c.servicesLabel}</p><h2 className="display refresh-title">{c.servicesTitle}</h2></div><p className="refresh-body max-w-md">{c.servicesIntro}</p></div><div className="refresh-services">{marketingServices.map(({ slug, icon: Icon, ...service }, i) => <Link key={slug} href={`/services/${slug}`} className="focus-ring refresh-service liquid-glass-card"><span aria-hidden="true" className="liquid-glass-rim" /><div className="flex items-center gap-3"><Icon size={21} aria-hidden="true" className="text-gold shrink-0" /><h3 className="text-lg font-semibold text-cream">{service[locale].title}</h3><span className="refresh-number ms-auto">0{i + 1}</span></div><p className="mt-6 text-xl font-medium text-cream">{service[locale].outcome}</p><p className="refresh-body mt-3">{service[locale].description}</p><p className="mt-6 text-xs leading-relaxed text-muted">{service[locale].scope}</p><span className="refresh-link mt-auto pt-7">{c.details}<ArrowRight size={16} className={direction} /></span></Link>)}</div></section>
    <section id="process" className="section-wrap refresh-section"><div className="refresh-method"><div><p className="refresh-label">{c.methodLabel}</p><h2 className="display refresh-title whitespace-pre-line">{c.methodTitle}</h2><p className="refresh-body mt-6 max-w-md">{c.methodIntro}</p></div><ol className="refresh-steps">{c.steps.map(([title, body, output], i) => <li key={title}><span className="refresh-number">0{i + 1}</span><div><h3 className="text-xl font-semibold text-cream">{title}</h3><p className="refresh-body mt-3">{body}</p><p className="mt-4 text-sm text-champagne">{output}</p></div></li>)}</ol></div><div id="architecture" className="refresh-engineering"><div><h3 className="text-base font-semibold text-cream">{c.approach}</h3><p className="refresh-body mt-2">{c.approachText}</p></div><Link href="/engineering" className="focus-ring refresh-link shrink-0">{c.engineering}<ArrowRight size={16} className={direction} /></Link></div></section>
    <section id="about" className="section-wrap refresh-section"><div className="refresh-about"><div><p className="refresh-label">{c.aboutLabel}</p><h2 className="display refresh-title whitespace-pre-line">{c.aboutTitle}</h2></div><div><p className="text-xl leading-relaxed text-cream">{c.aboutText}</p><p className="refresh-body mt-5">{c.aboutDetail}</p><Link href={locale === "ar" ? "/ar/about" : "/about"} className="focus-ring refresh-link mt-7">{c.aboutLink}<ArrowRight size={16} className={direction} /></Link></div></div></section>
    <section id="contact" className="section-wrap refresh-section"><div className="refresh-contact"><p className="refresh-label">{c.contactLabel}</p><h2 className="display refresh-contact-title whitespace-pre-line">{c.contactTitle}</h2><p className="refresh-body mx-auto mt-6 max-w-lg">{c.contactText}</p><button onClick={() => onOpenModal()} className="focus-ring refresh-primary mt-8">{c.primary}<ArrowRight size={17} className={direction} /></button><p className="mt-4 text-xs text-muted">{c.contactNote}</p><p className="mt-9 text-sm text-muted">{c.emailLabel} <a href="mailto:contact@vortexmind.co" className="focus-ring refresh-email" dir="ltr">contact@vortexmind.co</a></p></div></section>
  </main>;
}

export function MarketingFooter() {
  const { locale } = useLanguage();
  const ar = locale === "ar";
  const prefix = ar ? "/ar" : "";
  return <footer className="section-wrap refresh-footer"><div className="refresh-footer-grid"><div><Link href="/" className="focus-ring text-xl font-bold tracking-widest text-cream">VORTEX</Link><p className="mt-3 max-w-xs text-sm leading-relaxed text-muted">{ar ? "ذكاء اصطناعي خاص. وبرمجيات مبنية حول عملك." : "Private AI. Software built around your business."}</p><p className="mt-5 text-xs text-muted">{marketingCopy[locale].location}</p></div><nav aria-label={ar ? "الخدمات" : "Services"}><p className="refresh-label mb-5">{ar ? "الخدمات" : "Services"}</p>{marketingServices.map(s => <Link key={s.slug} href={`/services/${s.slug}`} className="focus-ring refresh-footer-link">{s[locale].title}</Link>)}</nav><nav aria-label={ar ? "الشركة" : "Company"}><p className="refresh-label mb-5">{ar ? "الشركة" : "Company"}</p>{[[`${prefix}/solutions`, ar ? "الحلول" : "Solutions"], ["/engineering", ar ? "نهجنا الهندسي" : "Engineering approach"], [`${prefix}/about`, ar ? "من نحن" : "About us"], [`${prefix}/insights`, ar ? "مقالات وأفكار" : "Insights"], ["/locations/jordan", ar ? "عمّان، الأردن" : "Amman, Jordan"], ["/?contact=1", ar ? "تواصل معنا" : "Contact"]].map(([href, label]) => <Link key={href} href={href} className="focus-ring refresh-footer-link">{label}</Link>)}<a href="mailto:contact@vortexmind.co" className="focus-ring refresh-footer-link" dir="ltr">contact@vortexmind.co</a></nav></div><div className="refresh-footer-bottom"><p>© {new Date().getFullYear()} VORTEX</p><div className="flex gap-5"><a className="focus-ring" href="https://www.linkedin.com/company/vortexmind/" target="_blank" rel="noreferrer" aria-label="LinkedIn"><Linkedin size={18} /></a><a className="focus-ring" href="https://www.instagram.com/vortexmind.tech/" target="_blank" rel="noreferrer" aria-label="Instagram"><Instagram size={18} /></a><a className="focus-ring" href="https://web.facebook.com/profile.php?id=61594225491476" target="_blank" rel="noreferrer" aria-label="Facebook"><Facebook size={18} /></a></div></div></footer>;
}
