"use client";

import Link from "@/components/localized-link";
import { AnimatedWorldMap } from "@/components/animated-world-map";
import { ArrowDown, ArrowRight, BrainCircuit, Check, Code2, Globe2, Layers3, Palette, Server, Sparkles, Workflow } from "lucide-react";
import { motion, useReducedMotion } from "framer-motion";

const builds = [
  ["التجارب الرقمية المؤسسية", "منصات مؤسسية تجمع بنية المعلومات والنظام البصري والأداء والوصول والمحتوى والتحليلات والتحويل.", "SEO، أنظمة المحتوى، القياس، الأداء، الوصول، ورحلات المستخدم."],
  ["التجارب التفاعلية", "مواقع تفاعلية عالية المستوى تستخدم الحركة والانتقالات والبيئات ثلاثية الأبعاد حيث تخدم التجربة.", "تفاعل مكاني، WebGL، حركة متجاوبة، وانتقالات سينمائية منضبطة."],
  ["تطبيقات الويب", "تطبيقات إنتاج تصل الواجهة بالهوية وواجهات API ومنطق الأعمال وقواعد البيانات والبنية.", "حسابات، صلاحيات، سير عمل، خدمات، بيانات، ونشر إنتاجي."],
  ["بوابات العملاء والشركاء", "بيئات آمنة ومصادق عليها للعملاء والموظفين والموردين والشركاء.", "الهوية، المستندات، الطلبات، الرسائل، ومسارات الخدمة الذاتية."],
  ["أنظمة التجارة والمعاملات", "منصات تصل المنتجات والحسابات والمخزون والدفع وسير العمل والتحليلات.", "دورة المعاملة، التكاملات، المخزون، الحسابات، والتشغيل خلف التجربة."],
  ["منصات المحتوى", "أنظمة نشر قابلة للتوسع تدير المحتوى المعقد دون التضحية بأداء الواجهة.", "نماذج المحتوى، الصلاحيات، سير المراجعة، البحث، والتسليم السريع."],
  ["منصات الأعمال الداخلية", "أدوات مركزة تمنح الفرق طريقة أوضح لإدارة العمليات والمعلومات والقرارات.", "قوائم العمل، الموافقات، الحالات، لوحات التحكم، والربط بالأنظمة القائمة."],
  ["تطبيقات الويب المدعومة بالذكاء", "واجهات تستخدم الذكاء عندما يصنع قيمة حقيقية للمستخدم أو للعمل.", "البحث الذكي، RAG، المساعدون، التوصيات، وأتمتة المستندات."],
] as const;

const layers = [["التجربة", "الواجهة والحركة والتفاعل", ["تصميم متجاوب", "نظام حركة", "الوصول"]], ["طبقة التفاعل", "الحالة والمكونات والسلوك", ["مكونات الواجهة", "التفاعلات", "الأداء"]], ["منطق التطبيق", "الحسابات وسير العمل", ["المصادقة", "لوحات التحكم", "قواعد الأعمال"]], ["واجهات API والتكاملات", "الخدمات والأنظمة المتصلة", ["REST APIs", "CRM و ERP", "الدفع"]], ["البيانات", "التخزين والبحث والتحليلات", ["SQL و NoSQL", "البحث", "التحليلات"]], ["البنية التحتية", "السحابة والنشر والتشغيل", ["الحاويات", "CI/CD", "المراقبة"]]] as const;
const process = [["الفهم", "فهم الجمهور والمحتوى والأنظمة والقيود قبل تشكيل التجربة."], ["المعمارية", "تحديد الحدود والتكاملات والبيانات ومسار النشر قبل التوسع."], ["التجربة", "تصميم الواجهة والتفاعل والحركة حول ما يجب أن يفعله المستخدم."], ["الهندسة", "بناء الواجهة والتطبيق وواجهات API والبيانات والبنية كمنتج واحد."], ["التحقق", "اختبار الأداء والوصول والتوافق ومسارات الفشل وسلوك الإنتاج."], ["الإطلاق", "نشر مضبوط وقابل للتكرار مع الرؤية والتوثيق."], ["التطور", "قياس المنصة وتحسينها وتوسيعها مع تغير المتطلبات."]] as const;

export function WebDevelopmentArabic() {
  const reducedMotion = useReducedMotion();
  return <main id="main-content" className="min-h-screen pt-32 sm:pt-44">
    <section className="relative overflow-hidden pb-24 sm:pb-36"><div aria-hidden="true" className="absolute inset-0 bg-[radial-gradient(circle_at_75%_20%,rgba(212,175,55,0.12),transparent_28rem)]" /><div className="section-wrap relative"><Link href="/#build" className="focus-ring inline-flex items-center gap-2 rounded-sm font-mono text-xs uppercase tracking-wider text-muted hover:text-champagne"><ArrowDown aria-hidden="true" size={14} className="rotate-90" /> استكشف الخدمات</Link><motion.div initial={reducedMotion ? false : { opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} className="mt-12 max-w-5xl"><p className="eyebrow mb-5"><Globe2 aria-hidden="true" size={13} className="text-gold" /> هندسة الويب / 02</p><h1 className="display max-w-4xl text-[clamp(3rem,8vw,7.2rem)] leading-[0.88] text-cream">أنظمة ويب مهندسة من التجربة إلى البنية التحتية.</h1><p className="mt-8 max-w-3xl text-lg leading-relaxed text-muted sm:text-xl">تهندس VORTEX التجربة البصرية والواجهة والتطبيق والبيانات والبنية خلف المنتجات الرقمية السريعة والقابلة للتوسع.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/?service=Website%20Development#contact" className="focus-ring inline-flex items-center gap-2 rounded-full bg-gradient-to-r from-gold via-champagne to-gold px-7 py-3.5 text-xs font-bold uppercase tracking-wider text-ink">ابدأ مشروع ويب <ArrowRight aria-hidden="true" size={14} /></Link><Link href="/#build" className="focus-ring inline-flex items-center gap-2 rounded-sm text-sm font-semibold text-champagne hover:text-cream">استكشف الخدمات <ArrowRight aria-hidden="true" size={14} /></Link></div></motion.div></div></section>

    <section className="section-wrap border-t border-gold/15 py-24 sm:py-36" aria-labelledby="arabic-web-build"><div className="mb-12 max-w-3xl"><p className="eyebrow mb-4"><Layers3 aria-hidden="true" size={13} className="text-gold" /> ما نبنيه</p><h2 id="arabic-web-build" className="display text-4xl leading-[0.95] text-cream sm:text-6xl">التجربة جزء من النظام.</h2><p className="mt-6 max-w-2xl text-base leading-relaxed text-muted sm:text-lg">كل نوع من المنتجات الرقمية يحتاج إلى قرارات هندسية مختلفة، من بنية المحتوى إلى التشغيل بعد الإطلاق.</p></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{builds.map(([title, description, detail], index) => <motion.article key={title} initial={reducedMotion ? false : { opacity: 0, y: 12 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.16 }} className="group relative flex min-h-[19rem] flex-col overflow-hidden rounded-[1.5rem] border border-gold/20 bg-[#2D0812]/50 p-6 hover:-translate-y-1 hover:border-gold/45"><div aria-hidden="true" className="absolute -end-10 -top-10 h-28 w-28 rounded-full border border-gold/20 transition-transform duration-500 group-hover:scale-150" /><div className="relative flex items-center justify-between"><div className="grid h-10 w-10 place-items-center rounded-xl border border-gold/30 bg-gold/10 text-gold"><Globe2 aria-hidden="true" size={19} /></div><span className="font-mono text-[0.62rem] text-muted">0{index + 1} / 08</span></div><h3 className="relative mt-7 font-display text-xl font-bold leading-tight text-cream">{title}</h3><p className="relative mt-3 text-sm leading-relaxed text-muted">{description}</p><p className="relative mt-auto border-t border-gold/15 pt-4 text-xs leading-relaxed text-cream/75">{detail}</p></motion.article>)}</div></section>

    <section className="relative overflow-hidden py-24 sm:py-36" aria-labelledby="arabic-web-stack"><div className="section-wrap"><div className="grid gap-12 lg:grid-cols-[0.75fr_1.25fr] lg:items-start"><div><p className="eyebrow mb-4"><Code2 aria-hidden="true" size={13} className="text-gold" /> هندسة كاملة</p><h2 id="arabic-web-stack" className="display max-w-xl text-4xl leading-[0.95] text-cream sm:text-6xl">ليست واجهة فقط.</h2><p className="mt-6 max-w-lg text-base leading-relaxed text-muted">الواجهة طبقة واحدة. يمكن لـ VORTEX هندسة التطبيق والتكاملات والبيانات والذكاء والبنية التي تعمل خلفها.</p></div><div className="grid gap-2 sm:grid-cols-2">{layers.map(([name, subtitle, items], index) => <div key={name} className={`rounded-xl border p-5 ${index === 0 ? "border-gold/45 bg-gold/10" : "border-gold/15 bg-[#2D0812]/45"}`}><div className="flex items-center gap-3"><Code2 aria-hidden="true" size={17} className="text-gold" /><h3 className="text-sm font-semibold text-cream">{name}</h3><span className="ms-auto font-mono text-[0.6rem] text-muted">0{index + 1}</span></div><p className="mt-3 text-xs text-muted">{subtitle}</p><div className="mt-4 flex flex-wrap gap-2">{items.map((item) => <span key={item} className="rounded-full border border-gold/15 px-2.5 py-1 font-mono text-[0.6rem] text-champagne">{item}</span>)}</div></div>)}</div></div></div></section>

    <section className="section-wrap border-y border-gold/15 py-24 sm:py-36" aria-labelledby="arabic-web-process"><div className="mb-12 max-w-3xl"><p className="eyebrow mb-4"><Workflow aria-hidden="true" size={13} className="text-gold" /> منهجية هندسة الويب</p><h2 id="arabic-web-process" className="display text-4xl leading-[0.95] text-cream sm:text-6xl">من البنية الأولى إلى الإنتاج.</h2><p className="mt-6 max-w-2xl text-base leading-relaxed text-muted sm:text-lg">مسار واضح يحافظ على قصد التجربة وتماسك النظام واستعداده للتطور.</p></div><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-4">{process.map(([title, description], index) => <div key={title} className="rounded-2xl border border-gold/15 bg-[#2D0812]/45 p-6"><div className="flex items-center justify-between"><Workflow aria-hidden="true" size={18} className="text-gold" /><span className="font-mono text-xs text-gold">0{index + 1}</span></div><h3 className="mt-7 font-display text-xl font-bold text-cream">{title}</h3><p className="mt-3 text-sm leading-relaxed text-muted">{description}</p></div>)}</div></section>

    <section className="section-wrap py-24 sm:py-36" aria-labelledby="arabic-web-design"><div className="mb-12 max-w-3xl"><p className="eyebrow mb-4"><Palette aria-hidden="true" size={13} className="text-gold" /> التصميم والهندسة</p><h2 id="arabic-web-design" className="display text-4xl leading-[0.95] text-cream sm:text-6xl">جميلة بما يكفي لتُذكر. متينة بما يكفي لتُعتمد.</h2></div><div className="grid gap-4 lg:grid-cols-2"><div className="rounded-[1.75rem] border border-gold/25 bg-[#2D0812]/55 p-7"><div className="flex items-center justify-between"><h3 className="font-display text-3xl font-bold text-cream">التصميم</h3><Palette aria-hidden="true" className="text-gold" /></div><ul className="mt-8 grid gap-3 sm:grid-cols-2">{["استراتيجية UX", "نظام واجهة", "ترجمة العلامة", "تصميم التفاعل", "تجارب متجاوبة", "الحركة", "ثلاثي الأبعاد", "الوصول"].map((item) => <li key={item} className="flex gap-2 text-sm text-muted"><Check aria-hidden="true" size={15} className="mt-0.5 shrink-0 text-gold" />{item}</li>)}</ul></div><div className="rounded-[1.75rem] border border-gold/25 bg-[#2D0812]/55 p-7"><div className="flex items-center justify-between"><h3 className="font-display text-3xl font-bold text-cream">الهندسة</h3><Server aria-hidden="true" className="text-gold" /></div><ul className="mt-8 grid gap-3 sm:grid-cols-2">{["أطر الواجهة الحديثة", "معمارية الخلفية", "واجهات API", "قواعد البيانات", "المصادقة", "النشر السحابي", "الأمان", "الأداء", "التكاملات", "تكامل الذكاء"].map((item) => <li key={item} className="flex gap-2 text-sm text-muted"><Check aria-hidden="true" size={15} className="mt-0.5 shrink-0 text-gold" />{item}</li>)}</ul></div></div></section>

    <section className="section-wrap border-y border-gold/15 py-24 sm:py-36" aria-labelledby="arabic-intelligence"><div className="grid gap-12 lg:grid-cols-[0.8fr_1.2fr] lg:items-center"><div><p className="eyebrow mb-4"><BrainCircuit aria-hidden="true" size={13} className="text-gold" /> طبقة الذكاء الاختيارية</p><h2 id="arabic-intelligence" className="display text-4xl leading-[0.95] text-cream sm:text-6xl">عندما يحتاج موقعك إلى الذكاء.</h2><p className="mt-6 max-w-lg text-base leading-relaxed text-muted">ليس الذكاء الاصطناعي ضرورياً لكل منتج رقمي. عندما يصنع قيمة حقيقية، يمكن هندسته داخل المنصة دون فصل عن بقية النظام.</p><Link href="/?service=AI%20System%20Development#contact" className="focus-ring mt-8 inline-flex items-center gap-2 rounded-sm text-sm font-semibold text-champagne hover:text-cream">ناقش طبقة الذكاء <ArrowRight aria-hidden="true" size={14} /></Link></div><div className="grid gap-3 sm:grid-cols-2">{["مساعدو الذكاء", "البحث الذكي", "أنظمة RAG", "أنظمة التوصية", "ذكاء المستندات", "الرؤية الحاسوبية", "سير العمل الآلي", "وكلاء الذكاء"].map((item) => <div key={item} className="flex items-center gap-3 rounded-xl border border-gold/15 bg-[#2D0812]/45 p-4 text-sm text-cream"><Sparkles aria-hidden="true" size={15} className="shrink-0 text-gold" />{item}</div>)}</div></div></section>

    <section id="contact" className="section-wrap pb-16 pt-8 sm:pb-24 sm:pt-12"><div className="relative isolate overflow-hidden rounded-[2.5rem] border border-gold/30 bg-[#1F050C] px-6 py-16 text-center sm:px-12 sm:py-24"><div aria-hidden="true" className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_50%_100%,rgba(212,175,55,0.2),transparent_60%),linear-gradient(135deg,rgba(229,195,120,0.05),transparent_40%,rgba(92,20,40,0.3))]" /><AnimatedWorldMap /><div className="relative z-10"><p className="eyebrow mb-4 justify-center"><Sparkles aria-hidden="true" size={13} className="text-gold" /> ابنِ الطبقة الرقمية</p><h2 className="display mx-auto max-w-4xl text-[clamp(2.5rem,6vw,5.5rem)] leading-[0.9] text-cream">من أول بكسل إلى بنية الإنتاج.</h2><p className="mx-auto mt-6 max-w-xl text-sm leading-relaxed text-muted sm:text-base">أخبرنا بما تبنيه. سنساعدك على تحديد النهج الصحيح.</p><div className="mt-9 flex flex-col justify-center gap-3 sm:flex-row"><Link href="/?service=Website%20Development#contact" className="focus-ring inline-flex items-center justify-center gap-2 rounded-full bg-gradient-to-r from-gold via-champagne to-gold px-8 py-4 text-xs font-bold uppercase tracking-wider text-ink">ابدأ مشروع ويب <Sparkles aria-hidden="true" size={15} /></Link><Link href="/#build" className="focus-ring inline-flex items-center justify-center gap-2 rounded-full border border-gold/30 px-8 py-4 text-xs font-bold uppercase tracking-wider text-champagne hover:border-gold hover:text-cream">استكشف الخدمات <ArrowRight aria-hidden="true" size={14} /></Link></div></div></div></section>
  </main>;
}
